# JSON Schema <http://json-schema.org/>
#
# Describes messages received from Indoktrinator.
#
---
oneOf:
  #
  # Message: plan
  #
  - type: object
    additionalProperties: false
    required: [id, type, plan]
    properties:
      id: {$ref: '#/definitions/uuid'}
      type: {enum: [plan]}
      plan: {$ref: '#/definitions/plan'}

  #
  # Message: layout
  #
  - type: object
    additionalProperties: false
    required: [id, type, layout]
    properties:
      id: {$ref: '#/definitions/uuid'}
      type: {enum: [layout]}
      layout: {$ref: '#/definitions/layout'}

definitions:
  uuid:
    type: string
    pattern: '^[0-9a-f]{32}$'

  url:
    type: string
    pattern: '://'

  timestamp:
    type: number

  mediaType:
    enum:
      - image
      - video

  plan:
    type: array
    items:
      type: object
      additionalProperties: false
      required: [start, end, type, url]
      properties:
        start: {$ref: '#/definitions/timestamp'}
        end: {$ref: '#/definitions/timestamp'}
        type: {$ref: '#/definitions/mediaType'}
        url: {$ref: '#/definitions/url'}
        layout: {$ref: '#/definitions/layout'}

  layout:
    type: object
    additionalProperties: false
    required: [mode]
    properties:
      mode: {enum: [full, sidebar, panel]}

      sidebar:
        oneOf:
          - enum: [null]
          - {$ref: '#/definitions/url'}

      panel:
        oneOf:
          - enum: [null]
          - {$ref: '#/definitions/url'}

# EOF
