# JSON Schema <http://json-schema.org/>
#
# Describes messages received from Indoktrinator.
#
---
type: object
additionalProperties: false
required: [id, type, plan]
properties:
  id: {$ref: '#/definitions/uuid'}
  type: {enum: [plan]}
  plan: {$ref: '#/definitions/plan'}

definitions:
  uuid:
    type: string
    pattern: '^[0-9a-f]{32}$'

  url:
    type: string
    pattern: '://'

  timestamp:
    type: number

  mediaType:
    enum: [image, video]

  plan:
    type: object
    additionalProperties: false
    required: [id, items, layouts, power]
    properties:
      id: {$ref: '#/definitions/uuid'}
      items:
        type: array
        items: {$ref: '#/definitions/item'}

      layouts:
        type: array
        items: {$ref: '#/definitions/layout'}

      power:
        type: array
        items: {$ref: '#/definitions/power'}

  item:
    type: object
    additionalProperties: false
    required: [start, end, type, url]
    properties:
      start: {$ref: '#/definitions/timestamp'}
      end: {$ref: '#/definitions/timestamp'}
      type: {$ref: '#/definitions/mediaType'}
      url: {$ref: '#/definitions/url'}

  layout:
    type: object
    additionalProperties: false
    required: [start, end, mode, sidebar, panel]
    properties:
      start:
        type: number

      end:
        type: number

      mode:
        enum: [full, sidebar, panel]

      sidebar:
        oneOf:
          - enum: [null]
          - {$ref: '#/definitions/url'}

      panel:
        oneOf:
          - enum: [null]
          - {$ref: '#/definitions/url'}

  power:
    type: object
    additionalProperties: false
    required: [start, end, power]
    properties:
      start:
        type: number

      end:
        type: number

      power:
        enum: ['on', 'standby']

# EOF
